[package]
name = "osmesa-sys"
version = "0.0.1"
authors = ["Daggerbot <daggerbot@gmail.com>"]
description = "OSMesa library bindings for Rust"
license = "CC0-1.0"
repository = "https://github.com/Daggerbot/osmesa-rs.git"

[dependencies]
gl = "*"
libc = "*"
